version: '3'
services:
  node: 
    image: node-18
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - 3000:3000
    depends_on:
      - mongo
      - redis
    command: npm start
  mongo: 
    image: mongo:latest
    ports:
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
  redis: 
    image: redis:latest
    ports: 
      - 6379:6379
volumes: 
  mongo-data:  
