apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers: 
        - name: nodejsapp-container
          image: mynode:latest
          ports: 
            - containerPort: 3002

